### ISSUE TITLE
Warp Radial doesn't work on Middle Button

### ISSUE THREAD

**Issue by StygianEmperor** [Crimix/warp-radial#10]
For some reason if I set my middle mouse button to bring up the radial menu, it does nothing in-game. Other buttons work.

**Comment by Crimix** [comment]
I will look into it.
By middle mouse, do you mean clicking down on the scroll wheel, which is used in vanilla to pick a block in creative?

**Comment by StygianEmperor** [comment]
Correct.

**Comment by Crimix** [comment]
This has been fixed in the newest version of BML, this will be pushed to Curseforge shortly
